{% set name = "google-cloud-cpp" %}
{% set version = "1.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f38ae4ab6f2ed7579a7ceb5d0b32ed04097da07bc898907ed01c8d840c2bdbce
  patches:
    - 0001-fix-storage-dep-windows.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("google-cloud-cpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - grpc-cpp
    - libprotobuf
  host:
    - abseil-cpp
    - libcrc32c
    - grpc-cpp
    - libcurl
    - libprotobuf
    - openssl
    - nlohmann_json
  run:

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - nlohmann_json
  source_files:
    - google/cloud/storage/quickstart/*.cc
    - google/cloud/storage/quickstart/CMakeLists.txt


about:
  home: https://github.com/googleapis/google-cloud-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Client Library for C++

extra:
  recipe-maintainers:
    - coryan
    - davidbrochart
    - xhochy
